deploy:
  name: Deploy to Azure
  runs-on: ubuntu-latest
  needs: test
  if: github.ref == 'refs/heads/main' # Only deploy from main branch

  defaults:
    run:
      working-directory: ./azure/project-2-cicd-pipeline

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to ACR
      run: |
        echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_NAME }}.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin

    - name: Build and push Docker image
      id: build-image
      run: |
        TIMESTAMP=$(date +%Y%m%d-%H%M%S)
        APP_NAME="mywebapp-$TIMESTAMP"
        echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV
        echo "app-name=$APP_NAME" >> $GITHUB_OUTPUT

        IMAGE_TAG="${{ secrets.ACR_NAME }}.azurecr.io/${APP_NAME}:latest"

        # Build and push image
        docker build -t $APP_NAME .
        docker tag $APP_NAME $IMAGE_TAG
        docker push $IMAGE_TAG

        echo "image-tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Deploy to Azure Container Instances
      run: |
        az container delete \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --name $APP_NAME \
          --yes || true

        az container create \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --name $APP_NAME \
          --image ${{ steps.build-image.outputs.image-tag }} \
          --registry-login-server ${{ secrets.ACR_NAME }}.azurecr.io \
          --registry-username ${{ secrets.ACR_USERNAME }} \
          --registry-password ${{ secrets.ACR_PASSWORD }} \
          --dns-name-label $APP_NAME \
          --os-type Linux \
          --ports 3001 \
          --environment-variables NODE_ENV=production \
          --cpu 1 \
          --memory 1.5 \
          --restart-policy Always \
          --location "southafricanorth"   # match your resource group region
